version: '3.1'

services:
  kee_web:
    image: antelle/keeweb
    restart: always
    volumes:
      - /home/chwech/docker/docker-kee-web/cert/:/etc/nginx/external/
    networks:
      - default
      - nginx_with_others
      
networks:
  nginx_with_others:
    external: true
