version: '3.1'

services:
  kee_web:
    image: antelle/keeweb
    restart: always
    volumes:
      - /home/chwech/docker/docker-kee-web/cert/:/etc/nginx/external/
    networks:
      - default
      - nginx_with_others
    build:
      args:
        - KEEWEB_CONFIG_URL=https://password.chwech.com/config.json
    environment:
      - KEEWEB_CONFIG_URL=https://password.chwech.com/config.json
      
networks:
  nginx_with_others:
    external: true
